import { type MarkedOptions } from "marked";
import sanitizeHtml from "sanitize-html";
import type { ParagraphClassNames } from "./types";

export const defaultParagraphClassNames: ParagraphClassNames = {
  root: "paragraph-content text-base leading-7 text-slate-800",
  p: "my-4 leading-7 text-slate-700",
  h1: "mt-10 text-4xl font-semibold tracking-tight text-slate-950",
  h2: "mt-8 text-3xl font-semibold tracking-tight text-slate-950",
  h3: "mt-6 text-2xl font-semibold tracking-tight text-slate-950",
  h4: "mt-5 text-xl font-semibold tracking-tight text-slate-950",
  h5: "mt-4 text-lg font-semibold tracking-tight text-slate-950",
  h6: "mt-4 text-base font-semibold tracking-tight text-slate-950",
  a: "font-medium text-slate-950 underline decoration-slate-300 underline-offset-4 transition-colors hover:text-slate-700",
  strong: "font-semibold text-slate-950",
  em: "italic",
  u: "underline underline-offset-4",
  s: "line-through",
  blockquote:
    "my-6 border-l-4 border-slate-200 pl-5 italic text-slate-600",
  code: "rounded-md bg-slate-100 px-1.5 py-0.5 font-mono text-[0.9em] text-slate-900",
  pre: "my-6 overflow-x-auto rounded-2xl bg-slate-950 p-4 text-sm text-slate-100",
  ul: "my-4 list-disc pl-6 text-slate-700",
  ol: "my-4 list-decimal pl-6 text-slate-700",
  li: "my-1.5",
  hr: "my-8 border-0 border-t border-slate-200",
  img: "block max-w-full rounded-2xl border border-slate-200 shadow-sm",
  figure: "my-6 flex flex-col items-center gap-2",
  figcaption: "text-sm text-slate-500",
  imageMeta: "flex max-w-full flex-col items-center gap-1 text-center",
  imageSlug: "text-xs font-medium uppercase tracking-[0.16em] text-slate-400",
  imageAlt: "text-sm text-slate-500",
  tableWrapper: "my-6 overflow-x-auto",
  table: "w-full min-w-[32rem] border-separate border-spacing-0 text-left text-sm text-slate-700",
  thead: "",
  tbody: "",
  tr: "",
  th: "border border-slate-200 bg-slate-50 px-4 py-3 font-semibold text-slate-950 first:rounded-tl-xl last:rounded-tr-xl",
  td: "border border-slate-200 px-4 py-3 align-top first:rounded-bl-xl last:rounded-br-xl",
  faq: "my-6 rounded-3xl border border-slate-200 bg-slate-50/80 p-3",
  collapsible: "rounded-2xl border border-slate-200 bg-white p-2 shadow-sm",
  summary:
    "cursor-pointer list-none rounded-xl px-3 py-3 font-medium text-slate-950 transition-colors hover:bg-slate-50",
  collapsibleContent: "px-3 pb-3 pt-2 text-slate-700",
  taskList: "my-4 list-none space-y-3 pl-0",
  taskItem: "flex list-none items-start gap-3 pl-0",
  taskCheckbox:
    "mt-1 h-4 w-4 rounded border-slate-300 text-slate-900 accent-slate-900",
};

export const defaultParagraphMarkedOptions: MarkedOptions = {
  async: false,
  breaks: false,
  gfm: true,
};

export const defaultParagraphSanitizeOptions: sanitizeHtml.IOptions = {
  allowedTags: Array.from(
    new Set([
      ...(sanitizeHtml.defaults.allowedTags ?? []),
      "img",
      "figure",
      "figcaption",
      "section",
      "details",
      "summary",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "input",
      "br",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
    ]),
  ),
  allowedAttributes: {
    ...sanitizeHtml.defaults.allowedAttributes,
    "*": ["class", "id"],
    a: [
      ...(sanitizeHtml.defaults.allowedAttributes.a ?? []),
      "href",
      "target",
      "rel",
      "title",
    ],
    img: [
      "src",
      "alt",
      "title",
      "width",
      "height",
      "loading",
      "srcset",
      "sizes",
      "data-media-id",
      "data-slug",
      "data-file-name",
      "data-mime-type",
      "data-size",
    ],
    section: ["class", "id", "data-type", "data-variant"],
    div: [
      "class",
      "id",
      "data-type",
      "data-variant",
      "data-media-id",
      "data-slug",
      "data-file-name",
      "data-mime-type",
      "data-size",
    ],
    span: ["class", "id", "data-type"],
    ul: ["class", "id", "data-type"],
    li: ["class", "id", "data-checked"],
    details: ["class", "id", "open", "data-type", "data-variant"],
    summary: ["class", "id"],
    input: ["class", "id", "type", "checked", "disabled", "aria-label"],
    table: ["class", "id"],
    thead: ["class", "id"],
    tbody: ["class", "id"],
    tr: ["class", "id"],
    th: ["class", "id", "colspan", "rowspan"],
    td: ["class", "id", "colspan", "rowspan"],
  },
  allowedSchemes: ["http", "https", "mailto", "tel"],
  parser: {
    lowerCaseAttributeNames: false,
  },
};
